apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: java-api
        image: ttl.sh/java-springboot-app:a48129c
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
